### ISSUE TITLE
MacITBase doesn't shutdown the mac

### ISSUE THREAD

**Issue by mjwall** [NationalSecurityAgency/qonduit#7]
Therefore resources are left open and over time you can run out of file handles

**Comment by ctubbsii** [comment]
Is this still a problem? I just did a build and did not see it still running. Please re-open if this is still an issue.

**Comment by mjwall** [comment]
When did you start using a mac @ctubbsii ?  

I no longer use a mac so I am not sure, it is fine to close this.
